spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nemodb
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8081
  error:
    include-message: always
